# Don't use the Travis Container-Based Infrastructure
sudo: true

language: java

matrix:
  fast_finish: true
  include:
  - os: linux
    jdk: oraclejdk8
    env: DISPLAY=:99.0

cache:
  directories:
  - $HOME/.m2

script:
- sh travis/build.sh

# Actions to perform after the build.
after_success:
- sh travis/tag_current_release.sh

deploy:
  - provider: releases
    api_key:
    - secure: "PlluitHHtisHpmawDLMV2oaBP4xvqzahuNC97xNlgaTN0ke9BNoIux0uq1u64U39TGR7qOtkz1SCARvk8zdDXMdoA/4yPyhlJ4QOVRHBzR8rxW10P2Sp0jar/NMEGHzA1Mx6lpd9iwcPN9FvKGBRGuwLFDL4aSx5oSrU872TmUOIpSv7LT0G5AElIllYSxUD3X4j3v+mFxNxZbMCFiNY65FzXfbvypguDiruEcX6Z/ypPqV+vvznx+yoYvUoky2UT9CEfMhjsWaA60E1oZjWt/fUNc5KZt3oFT8wOY/ReWl9MbquZkvhGa0OWTQxTDhvyLldkxgwb3UIOfJW06gooC/FILe40/G9tVHqu1rH74Yi86lHmuGgpPq+t7wT+192uPKsPNmj3Ypdh+dykMC5zgDCJAflzfwC5hHmReDRcN7Fn+JCY7pj292NFYucvMfC4ZRF68F7ieJJY+qVxstHvB8y+YX8D/Uwr/6Yw36Hc3YX7kU2U02cSZt7ngamAXBCU7rpEB1RsEUVmcANbGxW9CfIacvJCEiyt3j7aL4HTA69jC/0yA/LEYXFKSIW9oIfAyi5v/5/9c7GNEURXSTDeZyTdw9MtWli+0sUTnrLHtWhSpLs2CA37je2/c/hcKZLoE95M4fdOOUiE9sHb+2XUGmYTilITWMlIuh/WNmEgDs="
    
    file:
      - "repositories/omcri.product/target/products/omcri.product-linux.gtk.x86_64.zip"
      - "repositories/omcri.product/target/products/omcri.product-macosx.cocoa.x86_64.zip"
      - "repositories/omcri.product/target/products/omcri.product-win32.win32.x86_64.zip"
    skip_cleanup: true
    overwrite: true
    on:
      branch : master
      repo: omcri/cloudrobotics
     
after_deploy:
#- sh travis/deploy-maven-artifacts.sh

env:
  global:
  - secure: "PwN76kpYdYRSDYq7bBqDU8KW4nQItG7vr9UHmdftyeYFikTfBQRMeULDeprYvz8Q3mwPr8xhjA6WBlzVtNTvUZ7YyE7kSjVk1dwkDWBbBc+WZj3k91y5G1TB3ZIp/FDJQFioaF1/nnezdAOKjpZaWAkmZoWgQvHFstUxKTC7S20pEXIiW+hdRGjUnKX2bF7TpcIc/3AvMxWsGmmsDPAICBS3z40zHNmBMGxVBQlDkklerngGFwaLsS9LIh7VY4UFnnNDazy6wjVYMIPBau3nPOugiUGaij5zE3umAce5ZMiY+pORAoTf39Hgr1pgTdvuLfnnkPme9aCED9LOGdJf6S6VAIIsOqHlVMdVzh3OR2nrhE8DNqdDXdT+mjgdySbuQ2/KE/KPLfyTSwDBKQfwwQoA8pWWG5e+5bCHKqTCjdouXZ5maB94x/I6NfUmn62gvcHR7Idme88OFAqAWs0CGzxQLbOUSM0Fh1bunF5Olub0+6Tqwc11qdT7J5QEka7xA7C8L1x/SF1YWOIsxb2wn33t7+6Z2+t1nUhsCThJ0dMzn8MzSJflRZCXICqI6EJ2joTcIrNAc1izIAGq5l3GW7aqTG6CZQuoD0b16HdEhAdaq3WC4n/xeGaSFizan7bbQA7wuBg0HX90anTTetjz/i6dmDuYlYkXA8VOtza4DM8="

