<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="omcriall" nsURI="http://occiware.org/cloudrobotics/all/ecore"
    nsPrefix="omcriall">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="occi" value="http://schemas.ogf.org/occi/core/ecore"/>
    <details key="legomindstormnxt2" value="http://occiware.org/cloudrobotics/mindstormnxt/ecore"/>
    <details key="turtlebot" value="http://occiware.org/cloudrobotics/turtlebot/ecore"/>
    <details key="parrotminidrone" value="http://occiware.org/cloudrobotics/parrotminidrone/ecore"/>
    <details key="omcricore" value="http://occiware.org/cloudrobotics/core/ecore"/>
    <details key="parrotardrone" value="http://occiware.org/cloudrobotics/parrotardrone/ecore"/>
    <details key="legomindstormev3" value="http://occiware.org/cloudrobotics/mindstormev3/ecore"/>
  </eAnnotations>
</ecore:EPackage>
